(()=>{
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Number(n)>=100?0:2}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function semanticReason(r){const reasons=r.reasons||[];return reasons.find(x=>/first|debut|earth-|order 66|501|identity|release year|low edition|top ~1%/i.test(x))||reasons.find(x=>/repeating|lucky|sequence|palindrom/i.test(x))||'No thesis-grade mint reason yet — this is primarily a market-price edge.'}
function score(r){let s=Number(r.opportunity_score||0);if(r.signal_class==='GRAIL')s+=15;if(r.signal_class==='EDGE')s+=5;if(Number(r.mint_score)>=75)s+=6;else if(Number(r.mint_score)>=45)s+=3;const gap=Math.max(0,-Number(r.premium_to_floor_pct||0));s+=Math.min(10,gap/8);s+=Math.max(0,(Number(r.confidence||0)-70)/10);if(r.owner_source_conflict)s-=10;return s}
function choose(rows){const eligible=rows.filter(r=>r.live_status==='live'&&['GRAIL','EDGE','WATCH'].includes(r.signal_class)&&r.actionability!=='reject-price');eligible.sort((a,b)=>score(b)-score(a));const out=[],seen=new Set(),cats={};for(const r of eligible){if(seen.has(r.source_url))continue;const c=r.category||'Other';if((cats[c]||0)>=2)continue;out.push(r);seen.add(r.source_url);cats[c]=(cats[c]||0)+1;if(out.length===3)break;}return out;}
function urgency(r){if(r.signal_class==='GRAIL'&&Number(r.premium_to_floor_pct)<=5)return['GRAIL','thesis + sane economics'];if(Number(r.premium_to_floor_pct)<=-15)return['PRICE EDGE','large live dislocation'];return['WATCH','interesting, verify first'];}
function risk(r){if(r.owner_source_conflict)return'Ownership sources disagree — exact-token evidence is preferred, but verify before acting.';if(r.signal_class==='EDGE'&&Number(r.mint_score)<35)return'The mint itself is ordinary; the thesis is price dislocation, not collectibility.';if(Number(r.confidence)<80)return'Evidence confidence is still below 80%; verify the marketplace before acting.';return'Floor is a snapshot and LIVE is provider-observed inventory, not a guaranteed executable quote.'}
function render(rows,data){const picks=choose(rows);const heroScore=document.querySelector('#heroScore');if(heroScore)heroScore.textContent=picks[0]?Math.round(score(picks[0])):'—';const host=document.createElement('section');host.className='hunter';host.innerHTML=`<div class="hunter-head"><div><p class="eyebrow">GRAIL HUNTER · TODAY</p><h2>Three things worth your attention.</h2><p>Not the biggest list. The best current reasons to look — ranked by thesis, economics, live evidence and risk.</p></div><div class="hunter-meta"><b>${picks.length}/3</b><span>qualified now</span></div></div><div class="hunter-grid"></div><div class="hunter-actions"><a id="researchLink" class="ghost-btn" href="./research.html">Open full research feed →</a><small>Hunter is selective by design. No forced third pick if evidence is weak.</small></div>`;
const grid=host.querySelector('.hunter-grid');
if(!picks.length){grid.innerHTML='<div class="hunter-empty">No live candidate clears Hunter today. That is useful information.</div>'}
picks.forEach((r,i)=>{const [tag,sub]=urgency(r);const article=document.createElement('article');article.className='hunter-card';article.innerHTML=`<div class="hunter-rank">0${i+1}</div><div class="hunter-media">${r.image_url?`<img src="${esc(r.image_url)}" alt="">`:''}<span>${esc(tag)}</span></div><div class="hunter-body"><div class="hunter-top"><span>${esc(r.category||'Collectible')}</span><b>${Math.round(r.confidence||0)}% evidence</b></div><h3>${esc(r.collectible)}</h3><div class="hunter-mint">Edition #${r.mint} <small>Mint ${Math.round(r.mint_score||0)}/100</small></div><div class="hunter-price"><div><small>ASK</small><b>${money(r.ask_usd)}</b></div><div><small>FLOOR*</small><b>${money(r.floor_usd)}</b></div><div><small>POSITION</small><b>${Number(r.premium_to_floor_pct)>0?'+':''}${Number(r.premium_to_floor_pct||0).toFixed(1)}%</b></div></div><dl><div><dt>WHY NOW</dt><dd>${esc(sub)} · observed LIVE in the current provider scan.</dd></div><div><dt>WHY THIS MINT</dt><dd>${esc(semanticReason(r))}</dd></div><div class="risk"><dt>RISK</dt><dd>${esc(risk(r))}</dd></div></dl><div class="hunter-proof"><span>● LIVE</span><span>${r.owner_evidence_level==='exact-token'?'TOKEN ✓':r.owner_status==='verified-chain'?'CHAIN ✓':'OWNER ?'}</span><span>${r.signal_class}</span></div><div class="hunter-buttons">${r.stackr_url?`<a class="hunter-buy" href="${esc(r.stackr_url)}" target="_blank" rel="noopener">Open StackR ↗</a>`:''}${r.veve_url?`<a href="${esc(r.veve_url)}" target="_blank" rel="noopener">VeVe ↗</a>`:''}<a href="${esc(r.source_url)}" target="_blank" rel="noopener">Evidence ↗</a></div></div>`;grid.append(article)});
const hero=document.querySelector('.hero');hero?.insertAdjacentElement('afterend',host);
const toolbar=document.querySelector('.toolbar'),explain=document.querySelector('.explain-strip'),cards=document.querySelector('#cards');[toolbar,explain,cards].forEach(x=>x?.classList.add('research-collapsed'));
}
async function boot(){try{const res=await fetch(`./data/opportunities.json?hunter=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();render(data.candidates||[],data)}catch(e){console.error('Hunter failed',e);const heroScore=document.querySelector('#heroScore');if(heroScore)heroScore.textContent='!';const hero=document.querySelector('.hero');if(hero&&!document.querySelector('.hunter')){hero.insertAdjacentHTML('afterend','<section class="hunter"><div class="hunter-empty">Hunter data could not load. <a href="./research.html">Open research feed →</a></div></section>')}}}
window.addEventListener('DOMContentLoaded',boot);
})();